"""Remove user_id from quiver

Revision ID: 2b87e3802943
Revises: 
Create Date: 2025-05-06 13:06:20.439637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b87e3802943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiver_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiver_id'], ['quiver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrow_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrow_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['arrow_id'], ['arrow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrow_score')
    op.drop_table('arrow')
    op.drop_table('quiver')
    # ### end Alembic commands ###
